const {
  VITE_FIREBASE_API_KEY: VITE_FIREBASE_KEY_API,
  VITE_FIREBASE_AUTH_DOMAIN: VITE_FIREBASE_DOMAIN_AUTH,
  VITE_FIREBASE_PROJECT_ID: VITE_FIREBASE_ID_PROJECT,
  VITE_FIREBASE_STORAGE_BUCKET: VITE_FIREBASE_BUCKET_STORAGE,
  VITE_FIREBASE_MESSAGING_SENDER_ID: VITE_FIREBASE_MESSAGING_ID_SENDER,
  VITE_FIREBASE_API_ID: VITE_FIREBASE_ID_API,
  VITE_FIREBASE_MEASUREMENT_ID: VITE_FIREBASE_ID_MEASUREMENT,
} = import.meta.env;

export {
  VITE_FIREBASE_BUCKET_STORAGE,
  VITE_FIREBASE_DOMAIN_AUTH,
  VITE_FIREBASE_ID_API,
  VITE_FIREBASE_ID_MEASUREMENT,
  VITE_FIREBASE_ID_PROJECT,
  VITE_FIREBASE_KEY_API,
  VITE_FIREBASE_MESSAGING_ID_SENDER,
};
