export const PATH = {
  HOME: '/home',
  SIGN_UP: '/sign-up',
  MAIN_SIGN_UP: '/main_sign',
  LOGIN: '/login',
  PROFILE: '/profile/:id',
  FEED: '/feed',
  FEED_TWEET: '/feed/:id',
  EXPLORE: '/explore',
  NOTIFICATIONS: '/notifications',
  MESSAGES: '/messages',
  BOOKMARKS: '/bookmarks',
  LISTS: '/lists',
  MORE: '/more',
  NOT_FOUND: '*',
} as const;
